apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-dev-taxi
  namespace: dev-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBkbR/ZOwMrIegMWnoDDdOYKsEVmfUFAxCUoldtZEN0WOhgPIbZgEyfoEss6GqO3OkbJyXTxrXXP0nkSo688mOWxa8SX9Met/SUJGF5Y6RnT3iFRQcWsHkdlyNZrZz8xuZl1ML6+4ja9PgeWTeExTm3Uv8lZntPjC3ALvl8+xJy/If5we4x9Q0cVVWgMg+ufnnxhnYG7Q8i32RG1Vn07y/gHS7CvN7s15B9ZkPDd8JEEM2OonUGQ1M6gX6RyelsvvwJR8zMwPA29QjHrk2hA2M2PcBXK75YAS+1q3gZ4afvdvav9yVR4m0v2TlndjLEIrNp+05Vxt+pObPfzwyxMGKZ4Lr1DhpOUSWDC/NE+vxckLR7OtrQ59ixdcqBVhvTVvxLT40eV1IIrD80KK+/0WL2o3eL9Ag5xlEyaTbMPoBNQbx8e92yyq78OL7//fpm5GTV3ikpu0PtD2gS21MuYuNHo4bR8ErIRc5SCYDJNRuqL1x1pNEjWK2PC4798xUb+55X8Amq5grJpBMKpzc7ld5dqP7Rdp4pZ6uFGOkR3PWmIy56S5bGzUOUUMdGrxchUgM6YqtagwB2hiTjQ37hrq+c7QVyi0IjYZ0P8LDg5/BUuMuzA4Qy4wXFWk+RGwrgUuYEfXdHnNS7IiU3vEF2od3mYTI/f4tUs1kO9cuUhSmBcTlWg+aNe8WGCm1vUyelMQh1zXNFRmG49bPNMZGRgC2fXjYkhg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-dev-taxi
      namespace: dev-cicd
    type: Opaque
